### ISSUE TITLE
Connecting with Username and Password credentials

### ISSUE THREAD

**Issue by niravsh** [randomsync/robotframework-mqttlibrary#2]
Username_pw_set function of paho client isn't abstracted to the library. I am using this library for a device test where the application needs to connect to the broker with the right user credentials. Need to use this functionality available in Paho client. Also other credential related methods can be passed up to the library so that we can use these.

**Comment by randomsync** [comment]
@niravsh should be easy to add the username_pw_set() functionality in form of a keyword. I'll look into it but pull requests are welcome as well. Also, meanwhile you can use the `Publish Single` or `Publish Multiple` keywords which support auth with username/password: http://randomsync.github.io/robotframework-mqttlibrary/#Publish%20Single
